# Set the base image to Ubuntu
FROM nginx:latest

# File Maintainer
MAINTAINER ctrl.be

# Install Dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    apt-get -y install nano && \
    apt-get -y install unzip && \
    apt-get -y install git

# That's all folks


