# Set the base image to NGINX
FROM nginx:latest

# File Maintainer
MAINTAINER ctrl.be

# Install Dependencies
RUN \
 apt-get update && \
 apt-get install -y \
 curl \
 cron \
 nano \
 wget \
 git \
 unzip

# That's all folks


