version: '2.3'
services:
    application:
        image: tianon/true:latest
        volumes:
            - ./../data/www:/var/www/
            - ./../data/logs:/var/logs/
    varnish:
        build: image/cargo-varnish
        image: cargo-varnish
        ports:
            - "8080:80"
        mem_limit: 512m
        memswap_limit: 512m
        volumes:
            - ./varnish.conf:/etc/varnish/default.vcl
        depends_on:
            - www
        environment:
            VIRTUAL_HOST: $VIRTUAL_HOST
    www:
        image: nginx:latest
        mem_limit: 64m
        memswap_limit: 64m
        ports:
            - "80"
        volumes_from:
            - application
        volumes:
            - ./../data/logs/nginx-error.log:/var/log/nginx/error.log
            - ./../data/logs/nginx-access.log:/var/log/nginx/access.log
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build: image/cargo-php
        image: cargo-php
        mem_limit: 1024m
        memswap_limit: 1024m
        ports:
            - "9000"
        volumes_from:
            - application
        environment:
            PHP_TIMEOUT: 300s
            PHP_MEMORY_LIMIT: 512M
    civicrm:
        build: image/cargo-civicrm
        image: cargo-civicrm
        mem_limit: 512m
        memswap_limit: 512m
        volumes_from:
            - application
        depends_on:
            - php
            - mysql
        environment:
            PHP_TIMEOUT: 300s
    build:
        build: image/cargo-civicrm
        volumes_from:
            - application
        depends_on:
            - civicrm
        environment:
            - projectInput=$COMPOSE_PROJECT_NAME
            - enableCivicrm=$CIVICRM
            - civiUrl=$CIVICRM_URL
#        command: "bash /var/www/generate.sh"
    db_share:
      image: tianon/true:latest
      volumes:
          - ./../data/db/mysql/imports:/data/imports
          - ./../data/db/mysql/exports:/data/exports
    db_data:
      image: tianon/true:latest
      volumes:
          - ./../data/db/mysql/data:/var/lib/mysql
    mysql:
        image: mysql:5.7
        mem_limit: 2048m
        memswap_limit: 2048m
        ports:
            - "3306"
        volumes_from:
            - db_data
            - db_share
        volumes:
            - ./mysql.conf:/etc/mysql/conf.d/custom.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
