version: '2'
services:
    www:
        image: cargo:nginx
        mem_limit: 256m
        ports:
            - "8080:80"   
        volumes:
            - ./../data/www:/var/www/html
            - ./../data/logs/nginx-error.log:/var/log/nginx/error.log
            - ./../data/logs/nginx-access.log:/var/log/nginx/access.log
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - maersk-seacraft
    php:
        image: cargo:php
        ports:
            - "9000:9000"
        volumes:
            - ./../data/www:/var/www/html
        depends_on:
            - mysql
        networks:
            - maersk-seacraft
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_secret
        networks:
            - maersk-seacraft
networks:
    maersk-seacraft:
        driver: bridge