version: '2'
services:
    application:
        image: tianon/true
        volumes:
            - ./../data/www:/var/www/
            - ./../data/logs:/var/logs/
    www:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes_from:
            - application
        volumes:
            - ./../data/logs/nginx-error.log:/var/log/nginx/error.log
            - ./../data/logs/nginx-access.log:/var/log/nginx/access.log
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        image: cargo:php
        ports:
            - "8089:9000"
        volumes_from:
            - application
    drupal:
        image: cargo:drupal
        volumes_from:
            - application
    build:
        image: cargo:drupal
        volumes_from:
            - application
        depends_on:
            - drupal
        environment:
            - projectInput=demo
            - enableCivicrm=y
            - civiUrl=http://localhost:8080/
        command: "bash /var/www/generate.sh"
    mysql:
        image: mysql
        ports:
            - "8086:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
