version: '2'
services:
    application:
        image: tianon/true
        volumes:
            - ./../data/www:/var/www/
    www:
        image: nginx:latest
        mem_limit: 256m
        ports:
            - "8080:80"
        volumes_from:
            - application
        volumes:
            - ./../data/logs/nginx-error.log:/var/log/nginx/error.log
            - ./../data/logs/nginx-access.log:/var/log/nginx/access.log
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - maersk-seacraft
    php:
        image: cargo:php
        ports:
            - "9000:9000"
        volumes_from:
            - application
        networks:
            - maersk-seacraft
    drupal:
        image: cargo:drupal
        volumes_from:
            - application
        networks:
            - maersk-seacraft
    build:
        image: cargo:drupal
        volumes_from:
            - application
        depends_on:
            - drupal
        command: "bash /var/www/generate.sh"
        networks:
            - maersk-seacraft
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_secret
        networks:
            - maersk-seacraft
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8181:80"
        environment:
            PMA_HOST: mysql
        networks:
            - maersk-seacraft
networks:
    maersk-seacraft:
        driver: bridge