#!/usr/bin/env bash
T1=$(date +%s)

#! Start.
echo "*******"
echo "cleanup"
echo "*******"

#! Cleanup.
find . -name '._*' -type f -delete

#! Database variables.
dbUser='root'
dbPass='root'
dbHost='mysql'

#! Remove folders generated by script.
chmod -R 777 ./html
rm -rf ./html
rm -rf ./.git
rm ./.gitignore
rm ./exclude-list.txt
rm ./include-list.txt
mv _html html

#! Ask project name.
#echo "Insert Project name:"
#read projectInput
projectInput='demo'

#! Cleanup & display project name.
projectClean=${projectInput//_/}
projectClean=${projectClean// /_}
projectName=${projectClean//[^a-zA-Z0-9_]/}
echo "Project name: $projectInput converted to $projectName"

#! Remove database(s) via MySQL.
mysql -v -u $dbUser -p$dbPass -h $dbHost -e 'drop database '$projectName'_d'
mysql -v -u $dbUser -p$dbPass -h $dbHost -e 'drop database '$projectName'_c'

#! Stop timer.
T2=$(date +%s)
diffsec="$(expr $T2 - $T1)"
echo | awk -v D=$diffsec '{printf "Elapsed time: %02d:%02d:%02d\n",D/(60*60),D%(60*60)/60,D%60}'

#! End.
echo "******************"
echo "that's all folks!!"
echo "******************"