# Set the base image to PHP
FROM php:7-fpm

# File Maintainer
MAINTAINER ctrl.be

# Install PHP Dependencies
RUN docker-php-ext-install opcache pdo pdo_mysql mysqli

# Install Drush
# RUN apt-get -y install drush

# That's all folks
